version: "3"

services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-server-mqz
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      #SPRING_DATASOURCE_PLATFORM: mysql
      #MYSQL_SERVICE_HOST: 192.168.1.136 #nacos配置信息读取mysql
      #MYSQL_SERVICE_DB_NAME: test_nacos_config
      #MYSQL_SERVICE_PORT: 3306
      #MYSQL_SERVICE_USER: root
      #MYSQL_SERVICE_PASSWORD: 123456
    volumes:
      - /var/standalone-logs:/Applications/mqz/nacos/docker-nacos/log
    ports:
      - "8848:8848"
      - "9555:9555" 
    restart: on-failure

