server:
  port: 1122


spring:
  profiles:
    active: dev
  application:
    name: mini-cloud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  #nacos配置中心地址
#docker启动的nacos-server可以把8848端口映射成其他端口，避免nacos-server被攻击
#nacos:
#  config:
#    server-addr: 127.0.0.1:8848 #120.55.12.223:8848


  #nacos 服务注册中心的地址
#nacos:
#  discovery:
#    server-addr: 127.0.0.1:8848 #120.55.12.223:8848

